config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :products do
    member do
        get :toggle_status_buy
    end
  end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :user
    has_one_attached :image
    
    validates :name, presence: true
    validates :description, presence: true
    validates :cost, presence: true
    validates :address, presence: true
    validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

    has_many :products, dependent: :destroy # this takes care of all products assosiated with user
    before_save { self.email = email.downcase }
    validates :username, presence: true, uniqueness: {case_sensitive: false }
    validates :email, presence: true, uniqueness: {case_sensitive: false }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end
    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home #creating home action for pages controller basically action means the method/funtion
        redirect_to products_path if logged_in?
    end
    def about #about method/Action for peges controller 
        
    end
end

app/controllers/products_controller.rb
#controller going to look for new action under view/ products folder and then new 
class ProductsController < ApplicationController
    before_action :set_product, only: [:edit, :update, :show, :destroy, :toggle_status_buy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    # Get a list of all products visible to all user only
    # Requests: GET
    def index
        # products instance varible will have all products and then will iterate through all 
        @products = Product.all
    end
    
    # Requests: GET
    def new 
        #new action for adding new product in product controller to product tabl/relation
        @product = Product.new #creating instance variable
    end

    #to edit product details
    #request: GET 
    def edit
        #for edit action in product controller we have to find the product through id
    end
    
    #Request: POST
    def create 
        @product = Product.new(product_params)
        @product.user = current_user
        if @product.save
            flash[:success] = "product was successfully added"
            redirect_to product_path(@product)
        else
            render 'new'
        end
    end

    #to update product
    #Request: PATCH
    def update
        if @product.update(product_params)
            flash[:success] = "Product was successfully updated"
            redirect_to product_path(@product)
        else
            render 'edit'
        end
    end

    #to show products details
    #Request: GET
    def show
        # find products from params with appropriate ID
        # for example  product/(3 = id)
    end

    #to delete the products history/details
    #Request: Delete
    def destroy
        @product.destroy
        flash[:danger] = "Product was successfully deleted"
        redirect_to products_path
    end

    def toggle_status_buy
        if current_user.wallet >= @product.cost && logged_in?
            current_user.wallet = current_user.wallet - @product.cost
            @product.user_id = current_user.id
            @product.sold = true
            # current_user.wallet.save  #some error need to be fixed
            @product.save
            flash[:success] = "Product is succesfully purchased"
            redirect_to user_path(current_user)
        else
            flash[:info] = "You don't have sufficient amount to buy this product"
            redirect_to products_path
        end
    end

    private
        def product_params
            params.require(:product).permit(:name, :cost, :description, :age, :address, :image, :visibility)
        end
        def set_product
            @product = Product.find(params[:id])
        end
        def require_same_user
            if current_user != @product.user and !current_user.admin?
                flash[:danger] = "You can only edit or delete your own products"
                redirect_to root_path
            end
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "There was somthing wrong with your login information"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :show, :destroy]
    before_action :require_admin, only: [:destroy]

    # Requests: GET
    def index
        @users = User.all
    end
    
    # Requests: GET
    def new
        @user = User.new
    end

    #Request: POST
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the G:SHOP #{@user.username}"
            redirect_to products_path
        else
            render 'new'
        end
    end

    # Requests: GET
    def edit
    end

    #to update user
    #Request: PATCH
    def update
        if @user.update(user_params)
            flash[:success] = "Your account was successfully updated"
            redirect_to products_path
        else
            render 'edit'
        end
    end

    # Requests: GET
    def show
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all product added by user have been deleted"
        redirect_to users_path
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password, :wallet)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "You can peform those action to only your own account and products"
            redirect_to root_path
        end
    end
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Only admin user can perform that action"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="foter-icons footer-item ">
        <a href="https://www.instagram.com/gkc_3/"><img class="footer-icons" src="app/assets/images/instagram.png" alt=""></a>
        <a href="https://github.com/gaurav-chaurasia"><img class="footer-icons" src="app/assets/images/github.png" alt=""></a>
        <a href="https://www.linkedin.com/in/gaurav-chaurasia/"><img class="footer-icons" src="app/assets/images/linkedin.png" alt=""></a>
        <a href="https://www.facebook.com/profile.php?id=100008466213205"><img class="footer-icons" src="app/assets/images/facebook.png" alt=""></a>
    </div>
    <div class="footer-item">Copyright &copy;2020 All rights reserved | GAURAV CHAURASIA</div>
</div>

app/views/layouts/_messages.html.erb
 <%# display messages %>

 <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%= "#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
            </div>
        <% end %>
    </div>
</div>      

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%# <a class="navbar-brand" id="logo" href="#">G-SHOP</a> %>
      <%= link_to 'G:SHOP', root_path, class:"navbar-brand", id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Products',products_path %></li>
        <li><%= link_to 'User', users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu center">
              <li><a href="#">Books</a></li>
              <li><a href="#">Electronics</a></li>
              <li><a href="#">Cycles</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Old papers</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Gyan</a></li>
            </ul>
          </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><%= "@admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu center">
              <li><%= link_to 'Add new Products', new_product_path %></li>
              <li><%= link_to 'View your profile', user_path(current_user) %></li>
              <li><%= link_to 'Edit your profile', edit_user_path(current_user) %></li>
              <li> <%= link_to 'Delete your account', '#' %> </li>
              <li role="separator" class="divider"></li>
              <li class="center"><%= current_user.wallet %>&#x20B9;</li>
            </ul>
          </li>
          <li><%= link_to 'Log out', logout_path,method: :delete, class:"btn btn-danger", id:"logout-btn" %></li>
        <% else %>
          <li><%= link_to 'Log In', login_path, class:"btn btn-primary", id:"login-btn" %></li>
          <li><%= link_to 'Sign Up', signup_path, style:"padding: 1.5rem 4rem" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= current_user.username  if logged_in?%><%= ' | ' if logged_in?%>G:SHOP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# display messages %>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class = "container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    <%= debug(params) %>
  </body>
</html>

app/views/pages/about.html.erb
<%# this is going to be about page for the application %>
<h1>This is the About page for my app</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<%#this is going to be the home page for my application %>
<div class="jumbotron center">
    <h1>Welcome to G:Shop </h1>
    <%= link_to 'Sing up now', signup_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/products/_form.html.erb
<%= render 'shared/errors', obj: @product%>

<div class="row">
    <div class="col-sm-offset-2 col-xs-8">
        <%= form_for(@product, :html => { class: "form-horizontal"}) do |p| %>  
        <%# '@product' is an instanse variable passed from products controller through new action%>
        <%# form_for is an rails helper method %>
        
        <div class="form-group">
            <div class="contrl-lable col-sm-2">
                <%= p.label :Name  %>
            </div>
            <div class="col-sm-10">
                <%= p.text_field :name, class: "form-control", placeholder: "Name of product", autofocus: true %>
            </div>
        </div>
        
        <div class="form-group">
            <div class="contrl-lable col-sm-2">
                <%= p.label :Cost  %>
            </div>
            <div class="col-sm-10">
                <%= p.number_field :cost, class: "form-control", placeholder: "Cost of product",autofocus: true %>
            </div>
        </div>
        
        <div class="form-group">
            <div class="contrl-lable col-sm-2">
                <%= p.label :Description %>
            </div>
            <div class="col-sm-10">
                <%= p.text_area :description, rows: 5, class: "form-control", placeholder: "Description about product" %>
            </div>  
        </div>
        
        <div class="form-group">
            <div class="contrl-lable col-sm-2">
                <%= p.label :Age  %>
            </div>
            <div class="col-sm-10">
                <%= p.number_field :age, class: "form-control", placeholder: "Age of product" %>
            </div>
        </div>

        <div class="form-group">
            <div class="contrl-lable col-sm-2">
                <%= p.label :Address  %>
            </div>
            <div class="col-sm-10">
                <%= p.text_area :address, class: "form-control", placeholder: "Product location" %>
            </div>
        </div>
        
        <div class="form-group">
            <div class="contrl-lable col-sm-2">
                <%= p.label :Image  %>
            </div>
            <div class="col-sm-10">
                <%= p.file_field :image, class: "form-control", placeholder: "upload product's Image" %>
            </div>
        </div>

        <div class="form-group">
            <div class="contrl-lable col-sm-2">
                <%= p.label :Visibility  %>
            </div>
            <div class="col-sm-10">
                <%= p.check_box :visibility, class: "checkbox-inline input-checkbox" %>
            </div>
        </div>
        
        <div class="form-group center">
            <div cass="col-sm-10">
                <%= p.submit class: "btn btn-primary btn-md" %>
            </div>
        </div>

        <% end %>

        <div class="center" style="margin:2rem 0;">
           [ <%= link_to 'cancel and return to Product listing', products_path %> ]
        </div>
    </div>
</div>

app/views/products/edit.html.erb
<h1 class="center" style="margin:2rem 0rem 5rem 0;"> Editing existing Product details </h1>
<%# for adjusting boxes inline css used %>


<%# creating partials for removing repeaing code %>
<%# reference : https://guides.rubyonrails.org/layouts_and_rendering.html %>
<%= render 'form' %>

app/views/products/index.html.erb
<h1 class="center"> Listing all Product ready for sells </h1>

<% @products.each do |product|%>
<% if product.visibility == true %>
    <div class="center">
        <div class="col-sm-4 details">
            <div>
                <%= link_to image_tag(product.image, style: "width:100%; border-radius:1em 1em 0em 0em;"), product_path(product) if product.image.attached? %>
            </div>
            <div>
                <small> 
                    <strong>
                        <%= product.user.username if product.user %> | Sold-status: <%= product.sold %>
                    </strong><br>
                    added for sell: <%= time_ago_in_words(product.created_at)%> ago,
                    last updated: <%= time_ago_in_words(product.updated_at) %> ago 
                </small>
                <h2 class="center"><%= product.name %></h2>
                <h3><small>cost: </small><%= product.cost %> &#x20B9;</h3> 
                
                <h3>description</h3>
                <p><%= product.description%></p>
                <% if logged_in? && current_user == product.user %>
                    <%= link_to 'Edit the Details', edit_product_path(product), class:"btn btn-xs btn-primary show-btn" %>
                    <%= link_to 'Delete the product', product_path(product), method: :delete, data:{confirm: "Are you sure?"}, class:"btn btn-xs btn-danger show-btn" %>
                <% end %>
                <% if product.user == current_user %>
                    <%= link_to 'View the Details', product_path(product), class:"btn btn-xs btn-success show-btn" %>
                <% else %>
                    <%= link_to 'Buy the Product', product_path(product), class:"btn btn-xs btn-success show-btn" %>
                <% end %>
            </div>
       </div>
    </div>
<% end %>
<% end%>

app/views/products/new.html.erb
<h1 class="center" style="margin:2rem 0rem 5rem 0;"> Add New Products for selling </h1> 
<%# for adjusting boxes inline css used %>

<%# creating partials for removing repeaing code %>
<%# reference : https://guides.rubyonrails.org/layouts_and_rendering.html %>
<%= render 'form' %>

app/views/products/show.html.erb
<h2 class="center"><%= @product.name %></h2>
<div class="center">
    <div class="show-container">
        <div>
            <%= image_tag(@product.image, style: "width:100%; border-radius:2em 2em 0em 0em;") if @product.image.attached? %>
        </div>
        <div>
            <h3>cost</h3> 
            <p><%= @product.cost %> &#x20B9;</p>
            
            <h3>description</h3>
            <p><%= @product.description%></p>
            
            <h3>age</h3>
            <p><%= @product.age %></p>
            <hr>
            Seller Details
            <h2 class="center"><%= link_to @product.user.username, @product.user == current_user && logged_in? ? user_path(@product.user) : '#'%></h2>
            <small> 
                joined G:SHOP: <%= time_ago_in_words(@product.created_at)%> ago,
                last updated: <%= time_ago_in_words(@product.updated_at) %> ago 
            </small>
            
            
            <h3>address</h3>
            <p><%= @product.address%></p>
            
            <% if logged_in? && current_user == @product.user %>
                <%= link_to 'Edit the Details', edit_product_path, class:"btn btn-sm btn-primary show-btn" %>
                <%= link_to 'Delete the product', product_path(@product), method: :delete, data:{confirm: "Are you sure?"}, class:"btn btn-sm btn-danger show-btn" %>
            <% end %>

            <% if @product.user == current_user %>
                <%= link_to 'Back to product listing', products_path, class:"btn btn-sm btn-success show-btn" %>                
           <% else %>
                <%= link_to 'Buy Now', toggle_status_buy_product_path(@product), class:"btn btn-sm btn-success show-btn" %>
           <% end %>
        
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>    
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this product from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>  
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row center" style="margin:5rem;">
    <div class="col-sm-offset-2 col-xs-8">
        <%= form_for(@user, :html => { class: "form-horizontal"}) do |p| %>  
        <%# '@user' is an instanse variable passed from products controller through new action%>
        <%# form_for is an rails helper method %>
        <% if current_user == @user && !@user.admin? %>  
            <div class="form-group">
                <div class="contrl-lable col-sm-2">
                    <%= p.label :username  %>
                </div>
                <div class="col-sm-10">
                    <%= p.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="contrl-lable col-sm-2">
                    <%= p.label :Email  %>
                </div>
                <div class="col-sm-10">
                    <%= p.email_field :email, class: "form-control", placeholder: "Enter email" %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="contrl-lable col-sm-2">
                    <%= p.label :Password %>
                </div>
                <div class="col-sm-10">
                    <%= p.password_field :password, class: "form-control", placeholder: "Enter password" %>
                </div>  
            </div>
        <% end %>

        <% if current_user == @user && @user.admin? %>
            <div class="form-group">
                <div class="contrl-lable col-sm-2">
                    <%= p.label :username  %>
                </div>
                <div class="col-sm-10">
                    <%= p.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="contrl-lable col-sm-2">
                    <%= p.label :Email  %>
                </div>
                <div class="col-sm-10">
                    <%= p.email_field :email, class: "form-control", placeholder: "Enter email" %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="contrl-lable col-sm-2">
                    <%= p.label :Password %>
                </div>
                <div class="col-sm-10">
                    <%= p.password_field :password, class: "form-control", placeholder: "Enter password" %>
                </div>  
            </div>

            <div class="form-group">
                <div class="contrl-lable col-sm-2">
                    <%= p.label :Wallet  %>
                </div>
                <div class="col-sm-10">
                    <%= p.number_field :wallet, step: :any, class: "form-control", placeholder: "Current balance",autofocus: true %>
                </div>
            </div>
        <% end %>

        <% if current_user != @user && !@user.admin?%>
            <div class="form-group">
                <div class="contrl-lable col-sm-2">
                    <%= p.label :Wallet  %>
                </div>
                <div class="col-sm-10">
                    <%= p.number_field :wallet, step: :any, class: "form-control", placeholder: "Current balance",autofocus: true %>
                </div>
            </div>
        <% end %>

        <div class="form-group center" style=" margin:4rem 0;">
            <div cass="col-sm-10">
                <%= p.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn btn-primary btn-md") %>
            </div>
            <div class="center" style="margin:2rem;">
                [ <%= link_to 'cancel and return to Product listing', products_path %> ]
            </div>
        </div>

        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="center"> Edit your account </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="center"> All G:SHOP Users </h1>

    
<% @users.each do |user|%>
    <div class="center">
        <div class="col-sm-5 user-details">
            <h2 class="center"><%= link_to user.username, user == current_user ? user_path(user) : '#' %></h2>
            <small>
                <h5><%= pluralize(user.products.count,"product") if user.products %></h5>
            </small>
            <small> 
                joined G:SHOP: <%= time_ago_in_words(user.created_at)%> ago,
                last updated: <%= time_ago_in_words(user.updated_at) %> ago 
            </small><br><br>
            <% if logged_in? && current_user.admin? %>
                <%= link_to 'Delete your account', user_path(user), method: :delete, class:"btn btn-sm btn-danger" %>
                <%= link_to 'change wallet amount', edit_user_path(user), class:"btn btn-sm btn-success" %>
            <% end %>
            <% if logged_in? && !user.admin? &&  current_user == user %>
                <%= link_to 'Delete your account', '#', class:"btn btn-sm btn-danger", data: { confirm: "Only Admins can delete users so contact Admin for any such action"} %>
            <% end %>
       </div>
    </div>
<% end%>

app/views/users/new.html.erb
<h1 class="center"> Sign Up for G:SHOP </h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="center"> <%= @user.username %> </h1>

<% @user.products.each do |product|%>
    <div class="center">
        <div class="col-sm-4 details">
            <div>
                <%= link_to image_tag(product.image, style: "width:100%; border-radius:1em 1em 0em 0em;"), product_path(product) if product.image.attached? %>
            </div>
            <div>
                <small> 
                    <strong>
                        <%= product.user.username if product.user %>
                    </strong><br>
                    added for sell: <%= time_ago_in_words(product.created_at)%> ago,
                    last updated: <%= time_ago_in_words(product.updated_at) %> ago 
                    <strong>
                        <p>Visibility :<%= product.visibility%>
                    </strong>
                </small>
                <h2 class="center"><%= product.name %></h2>
                <h3><small>cost: </small><%= product.cost %> &#x20B9;</h3>
                <p>  </p> 
                
                <h3>description</h3>
                <p><%= product.description%></p>
                
                <% if logged_in? &&  current_user == @user %>
                    <%= link_to 'Edit the Details', edit_product_path(product), class:"btn btn-xs btn-primary show-btn" %>
                    <%= link_to 'Delete the product', product_path(product), method: :delete, data:{confirm: "Are you sure?"}, class:"btn btn-xs btn-danger show-btn" %>
                <% end %>
                <%= link_to 'view Details', product_path(product), class:"btn btn-xs btn-success show-btn" %>
            </div>
       </div>
    </div>
<% end%>